time="2025-10-30T00:35:32+01:00" level=warning msg="/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2022-24816/custom_no_tool/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
#1 [internal] load local bake definitions
#1 reading from stdin 1.40kB done
#1 DONE 0.0s

#2 [vulnerable_app internal] load build definition from Dockerfile
#2 transferring dockerfile: 812B done
#2 DONE 0.1s

#3 [geoserver internal] load build definition from Dockerfile
#3 transferring dockerfile: 141B done
#3 DONE 0.2s

#4 [geoserver internal] load metadata for docker.io/osgeo/geoserver:2.17.2
#4 ...

#5 [vulnerable_app internal] load metadata for docker.io/library/python:3.9-slim
#5 DONE 0.6s

#6 [vulnerable_app internal] load .dockerignore
#6 transferring context:
#6 transferring context: 2B done
#6 DONE 0.2s

#4 [geoserver internal] load metadata for docker.io/osgeo/geoserver:2.17.2
#4 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

#7 [vulnerable_app internal] load build context
#7 DONE 0.0s

#8 [vulnerable_app 1/7] FROM docker.io/library/python:3.9-slim@sha256:545badebace9a958b98d3e272f0f0d46c0a1a389ac77e24c33f2e7b548ce1b6b
#8 resolve docker.io/library/python:3.9-slim@sha256:545badebace9a958b98d3e272f0f0d46c0a1a389ac77e24c33f2e7b548ce1b6b
#8 resolve docker.io/library/python:3.9-slim@sha256:545badebace9a958b98d3e272f0f0d46c0a1a389ac77e24c33f2e7b548ce1b6b 0.3s done
#8 DONE 0.3s

#9 [vulnerable_app 2/7] WORKDIR /app
#9 CACHED

#7 [vulnerable_app internal] load build context
#7 transferring context: 1.19kB done
#7 DONE 0.1s

#10 [vulnerable_app 3/7] RUN apt-get update && apt-get install -y --no-install-recommends     gcc     libpq-dev     python3-dev     netcat-openbsd     dos2unix &&     rm -rf /var/lib/apt/lists/*
#10 CANCELED
------
 > [geoserver internal] load metadata for docker.io/osgeo/geoserver:2.17.2:
------
Dockerfile:1

--------------------

   1 | >>> FROM osgeo/geoserver:2.17.2

   2 |     RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*

--------------------

target geoserver: failed to solve: osgeo/geoserver:2.17.2: failed to resolve source metadata for docker.io/osgeo/geoserver:2.17.2: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

