#1 [internal] load local bake definitions
#1 reading from stdin 1.40kB done
#1 DONE 0.0s

#2 [geoserver internal] load build definition from Dockerfile
#2 transferring dockerfile: 254B done
#2 DONE 0.0s

#3 [vulnerable_app internal] load build definition from Dockerfile
#3 transferring dockerfile: 812B done
#3 DONE 0.0s

#4 [vulnerable_app internal] load metadata for docker.io/library/python:3.9-slim
#4 DONE 0.5s

#5 [geoserver internal] load metadata for docker.io/geoserver/geoserver:2.17.2
#5 ...

#6 [vulnerable_app internal] load .dockerignore
#6 transferring context: 2B done
#6 DONE 0.0s

#7 [vulnerable_app 1/7] FROM docker.io/library/python:3.9-slim@sha256:545badebace9a958b98d3e272f0f0d46c0a1a389ac77e24c33f2e7b548ce1b6b
#7 resolve docker.io/library/python:3.9-slim@sha256:545badebace9a958b98d3e272f0f0d46c0a1a389ac77e24c33f2e7b548ce1b6b 0.0s done
#7 DONE 0.0s

#8 [vulnerable_app 2/7] WORKDIR /app
#8 CACHED

#9 [vulnerable_app internal] load build context
#9 transferring context: 1.19kB done
#9 DONE 0.0s

#10 [vulnerable_app 3/7] RUN apt-get update && apt-get install -y --no-install-recommends     gcc     libpq-dev     python3-dev     netcat-openbsd     dos2unix &&     rm -rf /var/lib/apt/lists/*
#10 0.265 Hit:1 http://deb.debian.org/debian trixie InRelease
#10 ...

#5 [geoserver internal] load metadata for docker.io/geoserver/geoserver:2.17.2
#5 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

#10 [vulnerable_app 3/7] RUN apt-get update && apt-get install -y --no-install-recommends     gcc     libpq-dev     python3-dev     netcat-openbsd     dos2unix &&     rm -rf /var/lib/apt/lists/*
#10 0.269 Get:2 http://deb.debian.org/debian trixie-updates InRelease [47.3 kB]
#10 0.297 Get:3 http://deb.debian.org/debian-security trixie-security InRelease [43.4 kB]
#10 0.318 Get:4 http://deb.debian.org/debian trixie/main amd64 Packages [9669 kB]
#10 CANCELED
------
 > [geoserver internal] load metadata for docker.io/geoserver/geoserver:2.17.2:
------
Dockerfile:1

--------------------

   1 | >>> FROM geoserver/geoserver:2.17.2

   2 |     # Switch to root to install packages, then revert to the original nonâ€‘root user

   3 |     USER root

--------------------

target geoserver: failed to solve: geoserver/geoserver:2.17.2: failed to resolve source metadata for docker.io/geoserver/geoserver:2.17.2: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

