time="2025-11-01T18:11:45+01:00" level=warning msg="The \"MYSQL_ROOT_PASSWORD\" variable is not set. Defaulting to a blank string."
#1 [internal] load local bake definitions
#1 reading from stdin 1.38kB done
#1 DONE 0.0s

#2 [vulnerable_app internal] load build definition from Dockerfile
#2 transferring dockerfile: 292B done
#2 DONE 0.0s

#3 [flink internal] load build definition from Dockerfile
#3 transferring dockerfile: 142B done
#3 DONE 0.0s

#4 [flink internal] load metadata for docker.io/library/flink:1.10.2
#4 DONE 0.2s

#5 [vulnerable_app internal] load metadata for docker.io/library/python:3.9-slim
#5 ...

#6 [flink internal] load .dockerignore
#6 transferring context: 2B done
#6 DONE 0.0s

#7 [flink 1/2] FROM docker.io/library/flink:1.10.2@sha256:c6ee4be967ca86d8d99bdfc18fcaf84bbd18bf7a23c389919bfb9afdc1cb084b
#7 resolve docker.io/library/flink:1.10.2@sha256:c6ee4be967ca86d8d99bdfc18fcaf84bbd18bf7a23c389919bfb9afdc1cb084b 0.0s done
#7 DONE 0.2s

#5 [vulnerable_app internal] load metadata for docker.io/library/python:3.9-slim
#5 ...

#8 [flink 2/2] RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
#8 0.275 Ign:1 http://deb.debian.org/debian buster InRelease
#8 0.294 Ign:2 http://deb.debian.org/debian buster-updates InRelease
#8 0.312 Err:3 http://deb.debian.org/debian buster Release
#8 0.312   404  Not Found [IP: 151.101.242.132 80]
#8 0.330 Err:4 http://deb.debian.org/debian buster-updates Release
#8 0.330   404  Not Found [IP: 151.101.242.132 80]
#8 0.342 Ign:5 http://security.debian.org/debian-security buster/updates InRelease
#8 0.358 Err:6 http://security.debian.org/debian-security buster/updates Release
#8 0.358   404  Not Found [IP: 151.101.242.132 80]
#8 0.363 Reading package lists...
#8 0.371 E: The repository 'http://deb.debian.org/debian buster Release' does not have a Release file.
#8 0.371 E: The repository 'http://deb.debian.org/debian buster-updates Release' does not have a Release file.
#8 0.371 E: The repository 'http://security.debian.org/debian-security buster/updates Release' does not have a Release file.
#8 ERROR: process "/bin/sh -c apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

#5 [vulnerable_app internal] load metadata for docker.io/library/python:3.9-slim
#5 DONE 0.9s

#9 [vulnerable_app internal] load .dockerignore
#9 CANCELED
------
 > [flink 2/2] RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*:
0.312   404  Not Found [IP: 151.101.242.132 80]
0.330 Err:4 http://deb.debian.org/debian buster-updates Release
0.330   404  Not Found [IP: 151.101.242.132 80]
0.342 Ign:5 http://security.debian.org/debian-security buster/updates InRelease
0.358 Err:6 http://security.debian.org/debian-security buster/updates Release
0.358   404  Not Found [IP: 151.101.242.132 80]
0.363 Reading package lists...
0.371 E: The repository 'http://deb.debian.org/debian buster Release' does not have a Release file.
0.371 E: The repository 'http://deb.debian.org/debian buster-updates Release' does not have a Release file.
0.371 E: The repository 'http://security.debian.org/debian-security buster/updates Release' does not have a Release file.
------
Dockerfile:3

--------------------

   1 |     FROM flink:1.10.2

   2 |     USER root

   3 | >>> RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

   4 |     

--------------------

target flink: failed to solve: process "/bin/sh -c apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

