time="2025-08-10T16:51:45+02:00" level=warning msg="/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2021-42013/custom_no_tool/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
#1 [internal] load local bake definitions
#1 reading from stdin 707B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 351B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/httpd:2.4.50
#3 DONE 0.6s

#4 [internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [1/5] FROM docker.io/library/httpd:2.4.50@sha256:b73a8591d3f1f170568b501ce645dc900f8f1c4c697fbc2420cae3502ab5e02c
#5 resolve docker.io/library/httpd:2.4.50@sha256:b73a8591d3f1f170568b501ce645dc900f8f1c4c697fbc2420cae3502ab5e02c 0.0s done
#5 CACHED

#6 [internal] load build context
#6 transferring context: 1.89kB done
#6 DONE 0.0s

#7 [2/5] RUN apt-get update &&     apt-get install -y python3 &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
#7 0.383 Ign:1 http://security.debian.org/debian-security buster/updates InRelease
#7 0.412 Ign:2 http://deb.debian.org/debian buster InRelease
#7 0.415 Err:3 http://security.debian.org/debian-security buster/updates Release
#7 0.415   404  Not Found [IP: 151.101.2.132 80]
#7 0.442 Ign:4 http://deb.debian.org/debian buster-updates InRelease
#7 0.471 Err:5 http://deb.debian.org/debian buster Release
#7 0.471   404  Not Found [IP: 146.75.54.132 80]
#7 0.503 Err:6 http://deb.debian.org/debian buster-updates Release
#7 0.503   404  Not Found [IP: 146.75.54.132 80]
#7 0.510 Reading package lists...
#7 0.517 E: The repository 'http://security.debian.org/debian-security buster/updates Release' does not have a Release file.
#7 0.517 E: The repository 'http://deb.debian.org/debian buster Release' does not have a Release file.
#7 0.517 E: The repository 'http://deb.debian.org/debian buster-updates Release' does not have a Release file.
#7 ERROR: process "/bin/sh -c apt-get update &&     apt-get install -y python3 &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
------
 > [2/5] RUN apt-get update &&     apt-get install -y python3 &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*:
0.415   404  Not Found [IP: 151.101.2.132 80]
0.442 Ign:4 http://deb.debian.org/debian buster-updates InRelease
0.471 Err:5 http://deb.debian.org/debian buster Release
0.471   404  Not Found [IP: 146.75.54.132 80]
0.503 Err:6 http://deb.debian.org/debian buster-updates Release
0.503   404  Not Found [IP: 146.75.54.132 80]
0.510 Reading package lists...
0.517 E: The repository 'http://security.debian.org/debian-security buster/updates Release' does not have a Release file.
0.517 E: The repository 'http://deb.debian.org/debian buster Release' does not have a Release file.
0.517 E: The repository 'http://deb.debian.org/debian buster-updates Release' does not have a Release file.
------
Dockerfile:4

--------------------

   3 |     # Install Python in the same image

   4 | >>> RUN apt-get update && \

   5 | >>>     apt-get install -y python3 && \

   6 | >>>     apt-get clean && \

   7 | >>>     rm -rf /var/lib/apt/lists/*

   8 |     

--------------------

failed to solve: process "/bin/sh -c apt-get update &&     apt-get install -y python3 &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

