time="2025-11-01T17:11:09+01:00" level=warning msg="/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2021-26120/custom_no_tool/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
 docker Pulling 
 ae283de69b7d Pulling fs layer 
 1962c7344fe5 Pulling fs layer 
 72a5813f12bb Pulling fs layer 
 4f7dc993c79e Pulling fs layer 
 d39d95e4997f Pulling fs layer 
 aa7a3367c785 Pulling fs layer 
 801bfaa63ef2 Pulling fs layer 
 5e259227d438 Pulling fs layer 
 837d641dcbc6 Pulling fs layer 
 a38001158edd Pulling fs layer 
 7709f1e4daeb Pulling fs layer 
 d39d95e4997f Download complete 
 ae283de69b7d Downloading [>                                                  ]  1.049MB/69.46MB
 ae283de69b7d Downloading [=>                                                 ]  2.097MB/69.46MB
 1962c7344fe5 Download complete 
 7709f1e4daeb Download complete 
 ae283de69b7d Downloading [==>                                                ]  3.146MB/69.46MB
 5e259227d438 Download complete 
 72a5813f12bb Download complete 
 ae283de69b7d Downloading [==>                                                ]  3.146MB/69.46MB
 837d641dcbc6 Downloading [==================================================>]  1.284kB/1.284kB
 837d641dcbc6 Download complete 
 ae283de69b7d Downloading [==>                                                ]  3.146MB/69.46MB
 ae283de69b7d Downloading [===>                                               ]  4.194MB/69.46MB
 4f7dc993c79e Downloading [=========================>                         ]  1.049MB/2.039MB
 ae283de69b7d Downloading [===>                                               ]  5.243MB/69.46MB
 aa7a3367c785 Download complete 
 4f7dc993c79e Downloading [=========================>                         ]  1.049MB/2.039MB
 4f7dc993c79e Downloading [=========================>                         ]  1.049MB/2.039MB
 ae283de69b7d Downloading [===>                                               ]  5.243MB/69.46MB
 4f7dc993c79e Downloading [=========================>                         ]  1.049MB/2.039MB
 ae283de69b7d Downloading [====>                                              ]  6.291MB/69.46MB
 ae283de69b7d Downloading [=====>                                             ]   7.34MB/69.46MB
 4f7dc993c79e Downloading [=========================>                         ]  1.049MB/2.039MB
 4f7dc993c79e Downloading [=========================>                         ]  1.049MB/2.039MB
 ae283de69b7d Downloading [=====>                                             ]   7.34MB/69.46MB
 4f7dc993c79e Downloading [=========================>                         ]  1.049MB/2.039MB
 ae283de69b7d Downloading [=====>                                             ]   7.34MB/69.46MB
 801bfaa63ef2 Downloading [==================>                                ]  1.049MB/2.799MB
 4f7dc993c79e Downloading [==================================================>]  2.039MB/2.039MB
 ae283de69b7d Downloading [=====>                                             ]   7.34MB/69.46MB
 801bfaa63ef2 Downloading [==================>                                ]  1.049MB/2.799MB
 4f7dc993c79e Download complete 
 a38001158edd Downloading [========>                                          ]  1.049MB/5.998MB
 ae283de69b7d Downloading [=====>                                             ]  7.934MB/69.46MB
 801bfaa63ef2 Downloading [==================>                                ]  1.049MB/2.799MB
 801bfaa63ef2 Downloading [=====================================>             ]  2.097MB/2.799MB
 a38001158edd Downloading [========>                                          ]  1.049MB/5.998MB
 ae283de69b7d Downloading [======>                                            ]  8.389MB/69.46MB
 ae283de69b7d Downloading [======>                                            ]  8.389MB/69.46MB
 801bfaa63ef2 Downloading [=====================================>             ]  2.097MB/2.799MB
 a38001158edd Downloading [========>                                          ]  1.049MB/5.998MB
 ae283de69b7d Downloading [======>                                            ]  8.389MB/69.46MB
 801bfaa63ef2 Download complete 
 a38001158edd Downloading [========>                                          ]  1.049MB/5.998MB
 801bfaa63ef2 Extracting 1 s
 ae283de69b7d Downloading [======>                                            ]  9.437MB/69.46MB
 a38001158edd Downloading [========>                                          ]  1.049MB/5.998MB
 4f7dc993c79e Extracting 1 s
 801bfaa63ef2 Pull complete 
 a38001158edd Downloading [=================>                                 ]  2.097MB/5.998MB
 ae283de69b7d Downloading [======>                                            ]  9.437MB/69.46MB
 4f7dc993c79e Extracting 1 s
 a38001158edd Downloading [=================>                                 ]  2.097MB/5.998MB
 ae283de69b7d Downloading [======>                                            ]  9.437MB/69.46MB
 4f7dc993c79e Extracting 1 s
 a38001158edd Downloading [=================>                                 ]  2.097MB/5.998MB
 ae283de69b7d Downloading [=======>                                           ]  10.49MB/69.46MB
 4f7dc993c79e Pull complete 
 a38001158edd Downloading [=================>                                 ]  2.097MB/5.998MB
 ae283de69b7d Downloading [=======>                                           ]  10.49MB/69.46MB
 d39d95e4997f Pull complete 
 ae283de69b7d Downloading [=======>                                           ]  10.49MB/69.46MB
 a38001158edd Downloading [=================>                                 ]  2.097MB/5.998MB
 a38001158edd Downloading [==========================>                        ]  3.146MB/5.998MB
 ae283de69b7d Downloading [========>                                          ]  11.53MB/69.46MB
 a38001158edd Downloading [==========================>                        ]  3.146MB/5.998MB
 ae283de69b7d Downloading [========>                                          ]  11.53MB/69.46MB
 a38001158edd Downloading [==========================>                        ]  3.146MB/5.998MB
 ae283de69b7d Downloading [=========>                                         ]  12.58MB/69.46MB
 ae283de69b7d Downloading [=========>                                         ]  12.58MB/69.46MB
 a38001158edd Downloading [==========================>                        ]  3.146MB/5.998MB
 a38001158edd Downloading [==========================>                        ]  3.146MB/5.998MB
 ae283de69b7d Downloading [=========>                                         ]  13.63MB/69.46MB
 a38001158edd Downloading [==================================>                ]  4.194MB/5.998MB
 ae283de69b7d Downloading [=========>                                         ]  13.63MB/69.46MB
 ae283de69b7d Downloading [=========>                                         ]  13.63MB/69.46MB
 a38001158edd Downloading [==================================>                ]  4.194MB/5.998MB
 ae283de69b7d Downloading [==========>                                        ]  14.68MB/69.46MB
 a38001158edd Downloading [==================================>                ]  4.194MB/5.998MB
 a38001158edd Downloading [==================================>                ]  4.194MB/5.998MB
 ae283de69b7d Downloading [==========>                                        ]  14.68MB/69.46MB
 a38001158edd Downloading [===========================================>       ]  5.243MB/5.998MB
 ae283de69b7d Downloading [============>                                      ]  16.78MB/69.46MB
 a38001158edd Downloading [===========================================>       ]  5.243MB/5.998MB
 ae283de69b7d Downloading [============>                                      ]  17.83MB/69.46MB
 a38001158edd Download complete 
 ae283de69b7d Downloading [===============>                                   ]  20.97MB/69.46MB
 ae283de69b7d Downloading [================>                                  ]  23.07MB/69.46MB
 ae283de69b7d Downloading [=================>                                 ]  24.12MB/69.46MB
 ae283de69b7d Downloading [==================>                                ]  25.17MB/69.46MB
 ae283de69b7d Downloading [==================>                                ]  26.21MB/69.46MB
 ae283de69b7d Downloading [===================>                               ]  27.26MB/69.46MB
 ae283de69b7d Downloading [===================>                               ]  27.26MB/69.46MB
 ae283de69b7d Downloading [====================>                              ]  28.31MB/69.46MB
 ae283de69b7d Downloading [====================>                              ]  28.31MB/69.46MB
 ae283de69b7d Downloading [====================>                              ]  28.31MB/69.46MB
 ae283de69b7d Downloading [=====================>                             ]  29.36MB/69.46MB
 ae283de69b7d Downloading [=====================>                             ]  29.36MB/69.46MB
 ae283de69b7d Downloading [=====================>                             ]  30.41MB/69.46MB
 ae283de69b7d Downloading [=====================>                             ]  30.41MB/69.46MB
 ae283de69b7d Downloading [======================>                            ]  31.46MB/69.46MB
 ae283de69b7d Downloading [======================>                            ]  31.46MB/69.46MB
 ae283de69b7d Downloading [=======================>                           ]  32.51MB/69.46MB
 ae283de69b7d Downloading [=======================>                           ]  32.51MB/69.46MB
 ae283de69b7d Downloading [========================>                          ]  33.55MB/69.46MB
 ae283de69b7d Downloading [========================>                          ]  33.55MB/69.46MB
 ae283de69b7d Downloading [========================>                          ]   34.6MB/69.46MB
 ae283de69b7d Downloading [========================>                          ]   34.6MB/69.46MB
 ae283de69b7d Downloading [=========================>                         ]  35.65MB/69.46MB
 ae283de69b7d Downloading [=========================>                         ]  35.65MB/69.46MB
 ae283de69b7d Downloading [==========================>                        ]   36.7MB/69.46MB
 ae283de69b7d Downloading [==========================>                        ]   36.7MB/69.46MB
 ae283de69b7d Downloading [===========================>                       ]  37.75MB/69.46MB
 ae283de69b7d Downloading [===========================>                       ]  37.75MB/69.46MB
 ae283de69b7d Downloading [===========================>                       ]  37.75MB/69.46MB
 ae283de69b7d Downloading [===========================>                       ]   38.8MB/69.46MB
 ae283de69b7d Downloading [===========================>                       ]   38.8MB/69.46MB
 ae283de69b7d Downloading [============================>                      ]  39.85MB/69.46MB
 ae283de69b7d Downloading [============================>                      ]  39.85MB/69.46MB
 ae283de69b7d Downloading [=============================>                     ]  40.89MB/69.46MB
 ae283de69b7d Downloading [=============================>                     ]  40.89MB/69.46MB
 ae283de69b7d Downloading [==============================>                    ]  41.94MB/69.46MB
 ae283de69b7d Downloading [==============================>                    ]  41.94MB/69.46MB
 ae283de69b7d Downloading [==============================>                    ]  42.99MB/69.46MB
 ae283de69b7d Downloading [==============================>                    ]  42.99MB/69.46MB
 ae283de69b7d Downloading [===============================>                   ]  44.04MB/69.46MB
 ae283de69b7d Downloading [===============================>                   ]  44.04MB/69.46MB
 ae283de69b7d Downloading [================================>                  ]  45.09MB/69.46MB
 ae283de69b7d Downloading [================================>                  ]  45.09MB/69.46MB
 ae283de69b7d Downloading [=================================>                 ]  46.14MB/69.46MB
 ae283de69b7d Downloading [=================================>                 ]  46.14MB/69.46MB
 ae283de69b7d Downloading [=================================>                 ]  47.19MB/69.46MB
 ae283de69b7d Downloading [=================================>                 ]  47.19MB/69.46MB
 ae283de69b7d Downloading [==================================>                ]  48.23MB/69.46MB
 ae283de69b7d Downloading [===================================>               ]  49.28MB/69.46MB
 ae283de69b7d Downloading [====================================>              ]  51.38MB/69.46MB
 ae283de69b7d Downloading [=======================================>           ]  54.53MB/69.46MB
 ae283de69b7d Downloading [========================================>          ]  56.62MB/69.46MB
 ae283de69b7d Downloading [=========================================>         ]  57.67MB/69.46MB
 ae283de69b7d Downloading [=========================================>         ]  57.67MB/69.46MB
 ae283de69b7d Downloading [==========================================>        ]  58.72MB/69.46MB
 ae283de69b7d Downloading [==========================================>        ]  58.72MB/69.46MB
 ae283de69b7d Downloading [===========================================>       ]  59.77MB/69.46MB
 ae283de69b7d Downloading [===========================================>       ]  59.77MB/69.46MB
 ae283de69b7d Downloading [===========================================>       ]  60.82MB/69.46MB
 ae283de69b7d Downloading [===========================================>       ]  60.82MB/69.46MB
 ae283de69b7d Downloading [============================================>      ]  61.87MB/69.46MB
 ae283de69b7d Downloading [============================================>      ]  61.87MB/69.46MB
 ae283de69b7d Downloading [=============================================>     ]  62.91MB/69.46MB
 ae283de69b7d Downloading [=============================================>     ]  62.91MB/69.46MB
 ae283de69b7d Downloading [==============================================>    ]  63.96MB/69.46MB
 ae283de69b7d Downloading [==============================================>    ]  63.96MB/69.46MB
 ae283de69b7d Downloading [==============================================>    ]  65.01MB/69.46MB
 ae283de69b7d Downloading [==============================================>    ]  65.01MB/69.46MB
 ae283de69b7d Downloading [===============================================>   ]  66.06MB/69.46MB
 ae283de69b7d Downloading [===============================================>   ]  66.06MB/69.46MB
 ae283de69b7d Downloading [===============================================>   ]  66.06MB/69.46MB
 ae283de69b7d Downloading [================================================>  ]  67.11MB/69.46MB
 ae283de69b7d Downloading [================================================>  ]  67.11MB/69.46MB
 ae283de69b7d Downloading [=================================================> ]  68.16MB/69.46MB
 ae283de69b7d Downloading [=================================================> ]  68.16MB/69.46MB
 ae283de69b7d Downloading [==================================================>]  69.46MB/69.46MB
 ae283de69b7d Downloading [==================================================>]  69.46MB/69.46MB
 ae283de69b7d Download complete 
 ae283de69b7d Extracting 1 s
 ae283de69b7d Extracting 1 s
 ae283de69b7d Extracting 1 s
 ae283de69b7d Extracting 1 s
 ae283de69b7d Extracting 1 s
 ae283de69b7d Extracting 1 s
 ae283de69b7d Extracting 1 s
 ae283de69b7d Extracting 1 s
 ae283de69b7d Extracting 1 s
 ae283de69b7d Extracting 1 s
 1962c7344fe5 Extracting 1 s
 aa7a3367c785 Extracting 1 s
 ae283de69b7d Pull complete 
 1962c7344fe5 Pull complete 
 5e259227d438 Pull complete 
 aa7a3367c785 Pull complete 
 a38001158edd Extracting 1 s
 72a5813f12bb Pull complete 
 837d641dcbc6 Pull complete 
 a38001158edd Pull complete 
 7709f1e4daeb Pull complete 
 docker Pulled 
#1 [internal] load local bake definitions
#1 reading from stdin 1.35kB done
#1 DONE 0.0s

#2 [vulnerable_app internal] load build definition from Dockerfile
#2 transferring dockerfile: 250B done
#2 DONE 0.0s

#3 [db internal] load build definition from Dockerfile
#3 transferring dockerfile: 95B done
#3 DONE 0.0s

#4 [db internal] load metadata for docker.io/library/mysql:5.7
#4 ...

#5 [vulnerable_app internal] load metadata for docker.io/library/python:3.9-slim
#5 DONE 0.4s

#6 [vulnerable_app internal] load .dockerignore
#6 transferring context: 2B done
#6 DONE 0.0s

#7 [vulnerable_app internal] load build context
#7 transferring context: 1.27kB done
#7 DONE 0.0s

#8 [vulnerable_app 1/4] FROM docker.io/library/python:3.9-slim@sha256:2d97f6910b16bd338d3060f261f53f144965f755599aab1acda1e13cf1731b1b
#8 resolve docker.io/library/python:3.9-slim@sha256:2d97f6910b16bd338d3060f261f53f144965f755599aab1acda1e13cf1731b1b 0.0s done
#8 CACHED

#9 [vulnerable_app 2/4] RUN pip install flask docker
#9 ...

#4 [db internal] load metadata for docker.io/library/mysql:5.7
#4 DONE 1.0s

#10 [db internal] load .dockerignore
#10 transferring context: 2B done
#10 DONE 0.0s

#11 [db internal] load build context
#11 transferring context: 230B done
#11 DONE 0.0s

#12 [db 1/2] FROM docker.io/library/mysql:5.7@sha256:4bc6bc963e6d8443453676cae56536f4b8156d78bae03c0145cbe47c2aad73bb
#12 resolve docker.io/library/mysql:5.7@sha256:4bc6bc963e6d8443453676cae56536f4b8156d78bae03c0145cbe47c2aad73bb 0.0s done
#12 DONE 0.1s

#9 [vulnerable_app 2/4] RUN pip install flask docker
#9 ...

#13 [db 2/2] COPY init.sql /docker-entrypoint-initdb.d/
#13 DONE 0.4s

#14 [db] exporting to image
#14 exporting layers 0.1s done
#14 exporting manifest sha256:97f0b4b6dfa7427c44d22e608a2c4f0bdfc83f93c065412c5717db5306ceb56b 0.0s done
#14 exporting config sha256:9d664a1cb5801883dd84599e8057b96339b81ffc40e84cc21e2b90eac9021beb
#14 exporting config sha256:9d664a1cb5801883dd84599e8057b96339b81ffc40e84cc21e2b90eac9021beb 0.0s done
#14 exporting attestation manifest sha256:a6018c91f93a1f661c6ebaa7c397246acbb45c558765241dda125050b3b7948d 0.0s done
#14 exporting manifest list sha256:c5bf637da2fc4bcb70414781224de9fe1d653681ab3e997824c6c6c091520e5a 0.0s done
#14 naming to docker.io/library/vulnerable_mysql:latest done
#14 unpacking to docker.io/library/vulnerable_mysql:latest 0.0s done
#14 DONE 0.2s

#9 [vulnerable_app 2/4] RUN pip install flask docker
#9 ...

#15 [db] resolving provenance for metadata file
#15 DONE 0.0s

#9 [vulnerable_app 2/4] RUN pip install flask docker
#9 2.165 Collecting flask
#9 2.284   Downloading flask-3.1.2-py3-none-any.whl (103 kB)
#9 2.583      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.3/103.3 kB 329.1 kB/s eta 0:00:00
#9 2.670 Collecting docker
#9 2.717   Downloading docker-7.1.0-py3-none-any.whl (147 kB)
#9 2.846      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 kB 1.3 MB/s eta 0:00:00
#9 2.950 Collecting werkzeug>=3.1.0
#9 2.984   Downloading werkzeug-3.1.3-py3-none-any.whl (224 kB)
#9 3.208      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 975.8 kB/s eta 0:00:00
#9 3.296 Collecting jinja2>=3.1.2
#9 3.324   Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
#9 3.581      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.9/134.9 kB 557.4 kB/s eta 0:00:00
#9 3.748 Collecting importlib-metadata>=3.6.0
#9 3.781   Downloading importlib_metadata-8.7.0-py3-none-any.whl (27 kB)
#9 3.989 Collecting blinker>=1.9.0
#9 4.020   Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
#9 4.330 Collecting markupsafe>=2.1.1
#9 4.362   Downloading markupsafe-3.0.3-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (20 kB)
#9 4.500 Collecting click>=8.1.3
#9 4.550   Downloading click-8.1.8-py3-none-any.whl (98 kB)
#9 4.858      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.2/98.2 kB 367.2 kB/s eta 0:00:00
#9 4.911 Collecting itsdangerous>=2.2.0
#9 4.935   Downloading itsdangerous-2.2.0-py3-none-any.whl (16 kB)
#9 5.139 Collecting urllib3>=1.26.0
#9 5.164   Downloading urllib3-2.5.0-py3-none-any.whl (129 kB)
#9 6.059      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.8/129.8 kB 139.4 kB/s eta 0:00:00
#9 6.194 Collecting requests>=2.26.0
#9 6.291   Downloading requests-2.32.5-py3-none-any.whl (64 kB)
#9 6.411      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 kB 516.4 kB/s eta 0:00:00
#9 6.554 Collecting zipp>=3.20
#9 6.582   Downloading zipp-3.23.0-py3-none-any.whl (10 kB)
#9 6.765 Collecting certifi>=2017.4.17
#9 6.788   Downloading certifi-2025.10.5-py3-none-any.whl (163 kB)
#9 7.155      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.3/163.3 kB 447.4 kB/s eta 0:00:00
#9 7.260 Collecting idna<4,>=2.5
#9 7.334   Downloading idna-3.11-py3-none-any.whl (71 kB)
#9 7.499      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 kB 437.5 kB/s eta 0:00:00
#9 8.365 Collecting charset_normalizer<4,>=2
#9 8.400   Downloading charset_normalizer-3.4.4-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (153 kB)
#9 8.640      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.0/154.0 kB 708.1 kB/s eta 0:00:00
#9 8.822 Installing collected packages: zipp, urllib3, markupsafe, itsdangerous, idna, click, charset_normalizer, certifi, blinker, werkzeug, requests, jinja2, importlib-metadata, flask, docker
#9 9.523 Successfully installed blinker-1.9.0 certifi-2025.10.5 charset_normalizer-3.4.4 click-8.1.8 docker-7.1.0 flask-3.1.2 idna-3.11 importlib-metadata-8.7.0 itsdangerous-2.2.0 jinja2-3.1.6 markupsafe-3.0.3 requests-2.32.5 urllib3-2.5.0 werkzeug-3.1.3 zipp-3.23.0
#9 9.524 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#9 9.671 
#9 9.671 [notice] A new release of pip is available: 23.0.1 -> 25.3
#9 9.671 [notice] To update, run: pip install --upgrade pip
#9 DONE 9.8s

#16 [vulnerable_app 3/4] WORKDIR /app
#16 DONE 0.0s

#17 [vulnerable_app 4/4] COPY app.py /app/app.py
#17 DONE 0.0s

#18 [vulnerable_app] exporting to image
#18 exporting layers
#18 exporting layers 0.8s done
#18 exporting manifest sha256:5c606cc592eda864e6b954c004ed4a8ec4d0d263d5c857ea8c95b308a9ea6dc0 0.0s done
#18 exporting config sha256:22947ec54a4913e06bc8db7d222082e1f030a383ae9748ab9d9f32810ddd66a4 0.0s done
#18 exporting attestation manifest sha256:83cdfa7c44ae775db2200e1e77736308c766aa8179ef869e1031702e81606250 0.0s done
#18 exporting manifest list sha256:a39ca6f4f2944e99379f99f2fac00c78d6ec10390715ccb59250865b6ae656ca 0.0s done
#18 naming to docker.io/library/vulnerable_app:latest done
#18 unpacking to docker.io/library/vulnerable_app:latest
#18 unpacking to docker.io/library/vulnerable_app:latest 0.4s done
#18 DONE 1.2s

#19 [vulnerable_app] resolving provenance for metadata file
#19 DONE 0.0s
 vulnerable_app:latest  Built
 vulnerable_mysql:latest  Built
 Network custom_no_tool_default  Creating
 Network custom_no_tool_default  Created
 Container docker_dind  Creating
 Container vulnerable_mysql  Creating
 Container docker_dind  Created
 Container vulnerable_app  Creating
 Container vulnerable_mysql  Created
 Container vulnerable_app  Created
 Container docker_dind  Starting
 Container vulnerable_mysql  Starting
 Container docker_dind  Started
 Container vulnerable_app  Starting
 Container vulnerable_mysql  Started
 Container vulnerable_app  Started


sudo docker logs 72445f5306470bcd0463882a7f53abaf8b06b6aa03cdae2688be0232e4609e9d --details
STDOUT:  /certs/server/cert.pem: OK
 /certs/client/cert.pem: OK

STDERR:  Generating RSA private key, 4096 bit long modulus (2 primes)
 ....++++
 .............................................................++++
 e is 65537 (0x010001)
 Generating RSA private key, 4096 bit long modulus (2 primes)
 ...................................................................................................................................................++++
 ......................++++
 e is 65537 (0x010001)
 Signature ok
 subject=CN = docker:dind server
 Getting CA Private Key
 Generating RSA private key, 4096 bit long modulus (2 primes)
 .............................................................................................................................++++
 .........................................................................................................++++
 e is 65537 (0x010001)
 Signature ok
 subject=CN = docker:dind client
 Getting CA Private Key
 time="2025-11-01T16:11:39.888331318Z" level=info msg="Starting up"
 time="2025-11-01T16:11:39.890174699Z" level=warning msg="could not change group /var/run/docker.sock to docker: group docker not found"
 time="2025-11-01T16:11:39.891103745Z" level=warning msg="could not change group var/run/docker.sock to docker: group docker not found"
 time="2025-11-01T16:11:39.892129457Z" level=info msg="libcontainerd: started new containerd process" pid=59
 time="2025-11-01T16:11:39.892201207Z" level=info msg="parsed scheme: \"unix\"" module=grpc
 time="2025-11-01T16:11:39.892212815Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
 time="2025-11-01T16:11:39.892237633Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
 time="2025-11-01T16:11:39.892295773Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
 time="2025-11-01T16:11:39.904957773Z" level=info msg="starting containerd" revision=269548fa27e0089a8b8278fc4fc781d7f65a939b version=v1.4.3
 time="2025-11-01T16:11:39.921178946Z" level=info msg="loading plugin \"io.containerd.content.v1.content\"..." type=io.containerd.content.v1
 time="2025-11-01T16:11:39.922549699Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.aufs\"..." type=io.containerd.snapshotter.v1
 time="2025-11-01T16:11:39.964498952Z" level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.aufs\"..." error="aufs is not supported (modprobe aufs failed: exit status 1 \"ip: can't find device 'aufs'\\nmodprobe: can't change directory to '/lib/modules': No such file or directory\\n\"): skip plugin" type=io.containerd.snapshotter.v1
 time="2025-11-01T16:11:39.964542082Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.btrfs\"..." type=io.containerd.snapshotter.v1
 time="2025-11-01T16:11:39.965010808Z" level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.btrfs\"..." error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs (ext4) must be a btrfs filesystem to be used with the btrfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
 time="2025-11-01T16:11:39.965041830Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.devmapper\"..." type=io.containerd.snapshotter.v1
 time="2025-11-01T16:11:39.965063845Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.devmapper" error="devmapper not configured"
 time="2025-11-01T16:11:39.965074152Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.native\"..." type=io.containerd.snapshotter.v1
 time="2025-11-01T16:11:39.965440607Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.overlayfs\"..." type=io.containerd.snapshotter.v1
 time="2025-11-01T16:11:39.966212944Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.zfs\"..." type=io.containerd.snapshotter.v1
 time="2025-11-01T16:11:39.966366650Z" level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.zfs\"..." error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
 time="2025-11-01T16:11:39.966396071Z" level=info msg="loading plugin \"io.containerd.metadata.v1.bolt\"..." type=io.containerd.metadata.v1
 time="2025-11-01T16:11:39.966582601Z" level=warning msg="could not use snapshotter devmapper in metadata plugin" error="devmapper not configured"
 time="2025-11-01T16:11:39.966609519Z" level=info msg="metadata content store policy set" policy=shared
 time="2025-11-01T16:11:39.977302951Z" level=info msg="loading plugin \"io.containerd.differ.v1.walking\"..." type=io.containerd.differ.v1
 time="2025-11-01T16:11:39.977347082Z" level=info msg="loading plugin \"io.containerd.gc.v1.scheduler\"..." type=io.containerd.gc.v1
 time="2025-11-01T16:11:39.977391112Z" level=info msg="loading plugin \"io.containerd.service.v1.introspection-service\"..." type=io.containerd.service.v1
 time="2025-11-01T16:11:39.977448552Z" level=info msg="loading plugin \"io.containerd.service.v1.containers-service\"..." type=io.containerd.service.v1
 time="2025-11-01T16:11:39.977496085Z" level=info msg="loading plugin \"io.containerd.service.v1.content-service\"..." type=io.containerd.service.v1
 time="2025-11-01T16:11:39.977512597Z" level=info msg="loading plugin \"io.containerd.service.v1.diff-service\"..." type=io.containerd.service.v1
 time="2025-11-01T16:11:39.977521803Z" level=info msg="loading plugin \"io.containerd.service.v1.images-service\"..." type=io.containerd.service.v1
 time="2025-11-01T16:11:39.977531410Z" level=info msg="loading plugin \"io.containerd.service.v1.leases-service\"..." type=io.containerd.service.v1
 time="2025-11-01T16:11:39.977550123Z" level=info msg="loading plugin \"io.containerd.service.v1.namespaces-service\"..." type=io.containerd.service.v1
 time="2025-11-01T16:11:39.977579243Z" level=info msg="loading plugin \"io.containerd.service.v1.snapshots-service\"..." type=io.containerd.service.v1
 time="2025-11-01T16:11:39.977589950Z" level=info msg="loading plugin \"io.containerd.runtime.v1.linux\"..." type=io.containerd.runtime.v1
 time="2025-11-01T16:11:39.978149739Z" level=info msg="loading plugin \"io.containerd.runtime.v2.task\"..." type=io.containerd.runtime.v2
 time="2025-11-01T16:11:39.978502184Z" level=info msg="loading plugin \"io.containerd.monitor.v1.cgroups\"..." type=io.containerd.monitor.v1
 time="2025-11-01T16:11:39.978782679Z" level=info msg="loading plugin \"io.containerd.service.v1.tasks-service\"..." type=io.containerd.service.v1
 time="2025-11-01T16:11:39.978818804Z" level=info msg="loading plugin \"io.containerd.internal.v1.restart\"..." type=io.containerd.internal.v1
 time="2025-11-01T16:11:39.978859733Z" level=info msg="loading plugin \"io.containerd.grpc.v1.containers\"..." type=io.containerd.grpc.v1
 time="2025-11-01T16:11:39.978896458Z" level=info msg="loading plugin \"io.containerd.grpc.v1.content\"..." type=io.containerd.grpc.v1
 time="2025-11-01T16:11:39.978933584Z" level=info msg="loading plugin \"io.containerd.grpc.v1.diff\"..." type=io.containerd.grpc.v1
 time="2025-11-01T16:11:39.978972011Z" level=info msg="loading plugin \"io.containerd.grpc.v1.events\"..." type=io.containerd.grpc.v1
 time="2025-11-01T16:11:39.978995227Z" level=info msg="loading plugin \"io.containerd.grpc.v1.healthcheck\"..." type=io.containerd.grpc.v1
 time="2025-11-01T16:11:39.979027049Z" level=info msg="loading plugin \"io.containerd.grpc.v1.images\"..." type=io.containerd.grpc.v1
 time="2025-11-01T16:11:39.979037156Z" level=info msg="loading plugin \"io.containerd.grpc.v1.leases\"..." type=io.containerd.grpc.v1
 time="2025-11-01T16:11:39.979049164Z" level=info msg="loading plugin \"io.containerd.grpc.v1.namespaces\"..." type=io.containerd.grpc.v1
 time="2025-11-01T16:11:39.979081787Z" level=info msg="loading plugin \"io.containerd.internal.v1.opt\"..." type=io.containerd.internal.v1
 time="2025-11-01T16:11:39.979788779Z" level=info msg="loading plugin \"io.containerd.grpc.v1.snapshots\"..." type=io.containerd.grpc.v1
 time="2025-11-01T16:11:39.979822402Z" level=info msg="loading plugin \"io.containerd.grpc.v1.tasks\"..." type=io.containerd.grpc.v1
 time="2025-11-01T16:11:39.979833309Z" level=info msg="loading plugin \"io.containerd.grpc.v1.version\"..." type=io.containerd.grpc.v1
 time="2025-11-01T16:11:39.979843316Z" level=info msg="loading plugin \"io.containerd.grpc.v1.introspection\"..." type=io.containerd.grpc.v1
 time="2025-11-01T16:11:39.980330955Z" level=info msg=serving... address=/var/run/docker/containerd/containerd-debug.sock
 time="2025-11-01T16:11:39.980436128Z" level=info msg=serving... address=/var/run/docker/containerd/containerd.sock.ttrpc
 time="2025-11-01T16:11:39.980521188Z" level=info msg=serving... address=/var/run/docker/containerd/containerd.sock
 time="2025-11-01T16:11:39.980554811Z" level=info msg="containerd successfully booted in 0.077924s"
 time="2025-11-01T16:11:39.987879401Z" level=info msg="parsed scheme: \"unix\"" module=grpc
 time="2025-11-01T16:11:39.987901917Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
 time="2025-11-01T16:11:39.987919129Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
 time="2025-11-01T16:11:39.987925533Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
 time="2025-11-01T16:11:39.990832954Z" level=info msg="parsed scheme: \"unix\"" module=grpc
 time="2025-11-01T16:11:39.990881288Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
 time="2025-11-01T16:11:39.990898399Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
 time="2025-11-01T16:11:39.990904604Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
 time="2025-11-01T16:11:40.027702978Z" level=info msg="Loading containers: start."
 time="2025-11-01T16:11:40.100604643Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
 time="2025-11-01T16:11:40.147808448Z" level=info msg="Loading containers: done."
 time="2025-11-01T16:11:40.167288986Z" level=info msg="Docker daemon" commit=8891c58 graphdriver(s)=overlay2 version=20.10.2
 time="2025-11-01T16:11:40.168617810Z" level=info msg="Daemon has completed initialization"
 time="2025-11-01T16:11:40.213861653Z" level=info msg="API listen on /var/run/docker.sock"
 time="2025-11-01T16:11:40.217045066Z" level=info msg="API listen on [::]:2376"
 time="2025-11-01T16:11:40.220778160Z" level=info msg="API listen on [::]:2375"
 time="2025-11-01T16:11:40.227405966Z" level=info msg="API listen on var/run/docker.sock"




sudo docker inspect 72445f5306470bcd0463882a7f53abaf8b06b6aa03cdae2688be0232e4609e9d[
    {
        "Id": "72445f5306470bcd0463882a7f53abaf8b06b6aa03cdae2688be0232e4609e9d",
        "Created": "2025-11-01T16:11:37.359800652Z",
        "Path": "dockerd-entrypoint.sh",
        "Args": [
            "--host=tcp://0.0.0.0:2375",
            "-H",
            "unix://var/run/docker.sock"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 42036,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2025-11-01T16:11:37.66075871Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:8f4e9ddda1049e6935f9fc7f5cad0bd1001fbf59188616f19b620fd7b6e95ba2",
        "ResolvConfPath": "/var/lib/docker/containers/72445f5306470bcd0463882a7f53abaf8b06b6aa03cdae2688be0232e4609e9d/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/72445f5306470bcd0463882a7f53abaf8b06b6aa03cdae2688be0232e4609e9d/hostname",
        "HostsPath": "/var/lib/docker/containers/72445f5306470bcd0463882a7f53abaf8b06b6aa03cdae2688be0232e4609e9d/hosts",
        "LogPath": "/var/lib/docker/containers/72445f5306470bcd0463882a7f53abaf8b06b6aa03cdae2688be0232e4609e9d/72445f5306470bcd0463882a7f53abaf8b06b6aa03cdae2688be0232e4609e9d-json.log",
        "Name": "/docker_dind",
        "RestartCount": 0,
        "Driver": "overlayfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "custom_no_tool_default",
            "PortBindings": {
                "2375/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "2375"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "label=disable"
            ],
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": null,
            "Name": "overlayfs"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "dd40a9296572cebb287b9e6369ac774a88ee5f5e0d32ef20dc92e02773c91704",
                "Source": "/var/lib/docker/volumes/dd40a9296572cebb287b9e6369ac774a88ee5f5e0d32ef20dc92e02773c91704/_data",
                "Destination": "/var/lib/docker",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "72445f530647",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "2375/tcp": {},
                "2376/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DOCKER_VERSION=20.10.2",
                "DOCKER_TLS_CERTDIR=/certs",
                "DIND_COMMIT=ed89041433a031cafc0a0f19cfe573c31688d377"
            ],
            "Cmd": [
                "--host=tcp://0.0.0.0:2375",
                "-H",
                "unix://var/run/docker.sock"
            ],
            "Image": "docker:20.10.2-dind",
            "Volumes": {
                "/var/lib/docker": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "dockerd-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "52f213753123e928359a5fcdef2c5ccbbbe65a13a5ac6b8b66b987dc29cfbc2e",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "",
                "com.docker.compose.image": "sha256:8f4e9ddda1049e6935f9fc7f5cad0bd1001fbf59188616f19b620fd7b6e95ba2",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "custom_no_tool",
                "com.docker.compose.project.config_files": "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2021-26120/custom_no_tool/docker-compose.yml",
                "com.docker.compose.project.working_dir": "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2021-26120/custom_no_tool",
                "com.docker.compose.service": "docker",
                "com.docker.compose.version": "2.40.2",
                "desktop.docker.io/wsl-distro": "Ubuntu"
            },
            "StopTimeout": 1
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "6f83b38c5c8f82b90f26767b17357b4f458c2821800dfa70b5ebefd7866b278d",
            "SandboxKey": "/var/run/docker/netns/6f83b38c5c8f",
            "Ports": {
                "2375/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "2375"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "2375"
                    }
                ]
            },
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "custom_no_tool_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "docker_dind",
                        "docker"
                    ],
                    "MacAddress": "be:24:1f:0b:c2:e2",
                    "DriverOpts": null,
                    "GwPriority": 0,
                    "NetworkID": "e3fa0664563b7de23b0bd6de4ceae5b85ff8a24ae5b8ffe536f4db8abe63cf7f",
                    "EndpointID": "7067d92dfa97b4ca54887225ec1e6ac74ad063650376ef5d1cb1431398e63857",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DNSNames": [
                        "docker_dind",
                        "docker",
                        "72445f530647"
                    ]
                }
            }
        },
        "ImageManifestDescriptor": {
            "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
            "digest": "sha256:12521ff42db0d1e1d99f89c7dea6aa6e2d028c20cb42dad8285503735ddf678d",
            "size": 2614,
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        }
    }
]

sudo docker logs b47989baa34548b05da569edb5b11a149c80bff537fc3250b229a9e5a615a12f --details
STDOUT: 
STDERR:  Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 198, in _new_conn
     sock = connection.create_connection(
   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
     raise err
   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
     sock.connect(sa)
 ConnectionRefusedError: [Errno 111] Connection refused
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
     response = self._make_request(
   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 493, in _make_request
     conn.request(
   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 494, in request
     self.endheaders()
   File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
     self._send_output(message_body, encode_chunked=encode_chunked)
   File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
     self.send(msg)
   File "/usr/local/lib/python3.9/http/client.py", line 980, in send
     self.connect()
   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 325, in connect
     self.sock = self._new_conn()
   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 213, in _new_conn
     raise NewConnectionError(
 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7014707fb820>: Failed to establish a new connection: [Errno 111] Connection refused
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 644, in send
     resp = conn.urlopen(
   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 841, in urlopen
     retries = retries.increment(
   File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 519, in increment
     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
 urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='docker', port=2375): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7014707fb820>: Failed to establish a new connection: [Errno 111] Connection refused'))
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 223, in _retrieve_server_version
     return self.version(api_version=False)["ApiVersion"]
   File "/usr/local/lib/python3.9/site-packages/docker/api/daemon.py", line 181, in version
     return self._result(self._get(url), json=True)
   File "/usr/local/lib/python3.9/site-packages/docker/utils/decorators.py", line 44, in inner
     return f(self, *args, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 246, in _get
     return self.get(url, **self._set_request_timeout(kwargs))
   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
     return self.request("GET", url, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
     resp = self.send(prep, **send_kwargs)
   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
     r = adapter.send(request, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 677, in send
     raise ConnectionError(e, request=request)
 requests.exceptions.ConnectionError: HTTPConnectionPool(host='docker', port=2375): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7014707fb820>: Failed to establish a new connection: [Errno 111] Connection refused'))
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/app/app.py", line 8, in <module>
     client = docker.DockerClient(base_url='tcp://docker:2375')
   File "/usr/local/lib/python3.9/site-packages/docker/client.py", line 45, in __init__
     self.api = APIClient(*args, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 207, in __init__
     self._version = self._retrieve_server_version()
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 230, in _retrieve_server_version
     raise DockerException(
 docker.errors.DockerException: Error while fetching server API version: HTTPConnectionPool(host='docker', port=2375): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7014707fb820>: Failed to establish a new connection: [Errno 111] Connection refused'))
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 198, in _new_conn
     sock = connection.create_connection(
   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
     raise err
   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
     sock.connect(sa)
 ConnectionRefusedError: [Errno 111] Connection refused
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
     response = self._make_request(
   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 493, in _make_request
     conn.request(
   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 494, in request
     self.endheaders()
   File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
     self._send_output(message_body, encode_chunked=encode_chunked)
   File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
     self.send(msg)
   File "/usr/local/lib/python3.9/http/client.py", line 980, in send
     self.connect()
   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 325, in connect
     self.sock = self._new_conn()
   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 213, in _new_conn
     raise NewConnectionError(
 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7b8f7da2b460>: Failed to establish a new connection: [Errno 111] Connection refused
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 644, in send
     resp = conn.urlopen(
   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 841, in urlopen
     retries = retries.increment(
   File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 519, in increment
     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
 urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='docker', port=2375): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b8f7da2b460>: Failed to establish a new connection: [Errno 111] Connection refused'))
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 223, in _retrieve_server_version
     return self.version(api_version=False)["ApiVersion"]
   File "/usr/local/lib/python3.9/site-packages/docker/api/daemon.py", line 181, in version
     return self._result(self._get(url), json=True)
   File "/usr/local/lib/python3.9/site-packages/docker/utils/decorators.py", line 44, in inner
     return f(self, *args, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 246, in _get
     return self.get(url, **self._set_request_timeout(kwargs))
   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
     return self.request("GET", url, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
     resp = self.send(prep, **send_kwargs)
   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
     r = adapter.send(request, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 677, in send
     raise ConnectionError(e, request=request)
 requests.exceptions.ConnectionError: HTTPConnectionPool(host='docker', port=2375): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b8f7da2b460>: Failed to establish a new connection: [Errno 111] Connection refused'))
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/app/app.py", line 8, in <module>
     client = docker.DockerClient(base_url='tcp://docker:2375')
   File "/usr/local/lib/python3.9/site-packages/docker/client.py", line 45, in __init__
     self.api = APIClient(*args, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 207, in __init__
     self._version = self._retrieve_server_version()
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 230, in _retrieve_server_version
     raise DockerException(
 docker.errors.DockerException: Error while fetching server API version: HTTPConnectionPool(host='docker', port=2375): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b8f7da2b460>: Failed to establish a new connection: [Errno 111] Connection refused'))
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 275, in _raise_for_status
     response.raise_for_status()
   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1026, in raise_for_status
     raise HTTPError(http_error_msg, response=self)
 requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker:2375/version
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 223, in _retrieve_server_version
     return self.version(api_version=False)["ApiVersion"]
   File "/usr/local/lib/python3.9/site-packages/docker/api/daemon.py", line 181, in version
     return self._result(self._get(url), json=True)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 281, in _result
     self._raise_for_status(response)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 277, in _raise_for_status
     raise create_api_error_from_http_exception(e) from e
   File "/usr/local/lib/python3.9/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
     raise cls(e, response=response, explanation=explanation) from e
 docker.errors.APIError: 400 Client Error for http://docker:2375/version: Bad Request ("Client sent an HTTP request to an HTTPS server.")
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/app/app.py", line 8, in <module>
     client = docker.DockerClient(base_url='tcp://docker:2375')
   File "/usr/local/lib/python3.9/site-packages/docker/client.py", line 45, in __init__
     self.api = APIClient(*args, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 207, in __init__
     self._version = self._retrieve_server_version()
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 230, in _retrieve_server_version
     raise DockerException(
 docker.errors.DockerException: Error while fetching server API version: 400 Client Error for http://docker:2375/version: Bad Request ("Client sent an HTTP request to an HTTPS server.")
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 275, in _raise_for_status
     response.raise_for_status()
   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1026, in raise_for_status
     raise HTTPError(http_error_msg, response=self)
 requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker:2375/version
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 223, in _retrieve_server_version
     return self.version(api_version=False)["ApiVersion"]
   File "/usr/local/lib/python3.9/site-packages/docker/api/daemon.py", line 181, in version
     return self._result(self._get(url), json=True)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 281, in _result
     self._raise_for_status(response)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 277, in _raise_for_status
     raise create_api_error_from_http_exception(e) from e
   File "/usr/local/lib/python3.9/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
     raise cls(e, response=response, explanation=explanation) from e
 docker.errors.APIError: 400 Client Error for http://docker:2375/version: Bad Request ("Client sent an HTTP request to an HTTPS server.")
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/app/app.py", line 8, in <module>
     client = docker.DockerClient(base_url='tcp://docker:2375')
   File "/usr/local/lib/python3.9/site-packages/docker/client.py", line 45, in __init__
     self.api = APIClient(*args, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 207, in __init__
     self._version = self._retrieve_server_version()
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 230, in _retrieve_server_version
     raise DockerException(
 docker.errors.DockerException: Error while fetching server API version: 400 Client Error for http://docker:2375/version: Bad Request ("Client sent an HTTP request to an HTTPS server.")
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 275, in _raise_for_status
     response.raise_for_status()
   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1026, in raise_for_status
     raise HTTPError(http_error_msg, response=self)
 requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker:2375/version
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 223, in _retrieve_server_version
     return self.version(api_version=False)["ApiVersion"]
   File "/usr/local/lib/python3.9/site-packages/docker/api/daemon.py", line 181, in version
     return self._result(self._get(url), json=True)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 281, in _result
     self._raise_for_status(response)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 277, in _raise_for_status
     raise create_api_error_from_http_exception(e) from e
   File "/usr/local/lib/python3.9/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
     raise cls(e, response=response, explanation=explanation) from e
 docker.errors.APIError: 400 Client Error for http://docker:2375/version: Bad Request ("Client sent an HTTP request to an HTTPS server.")
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/app/app.py", line 8, in <module>
     client = docker.DockerClient(base_url='tcp://docker:2375')
   File "/usr/local/lib/python3.9/site-packages/docker/client.py", line 45, in __init__
     self.api = APIClient(*args, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 207, in __init__
     self._version = self._retrieve_server_version()
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 230, in _retrieve_server_version
     raise DockerException(
 docker.errors.DockerException: Error while fetching server API version: 400 Client Error for http://docker:2375/version: Bad Request ("Client sent an HTTP request to an HTTPS server.")
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 275, in _raise_for_status
     response.raise_for_status()
   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1026, in raise_for_status
     raise HTTPError(http_error_msg, response=self)
 requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker:2375/version
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 223, in _retrieve_server_version
     return self.version(api_version=False)["ApiVersion"]
   File "/usr/local/lib/python3.9/site-packages/docker/api/daemon.py", line 181, in version
     return self._result(self._get(url), json=True)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 281, in _result
     self._raise_for_status(response)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 277, in _raise_for_status
     raise create_api_error_from_http_exception(e) from e
   File "/usr/local/lib/python3.9/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
     raise cls(e, response=response, explanation=explanation) from e
 docker.errors.APIError: 400 Client Error for http://docker:2375/version: Bad Request ("Client sent an HTTP request to an HTTPS server.")
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/app/app.py", line 8, in <module>
     client = docker.DockerClient(base_url='tcp://docker:2375')
   File "/usr/local/lib/python3.9/site-packages/docker/client.py", line 45, in __init__
     self.api = APIClient(*args, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 207, in __init__
     self._version = self._retrieve_server_version()
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 230, in _retrieve_server_version
     raise DockerException(
 docker.errors.DockerException: Error while fetching server API version: 400 Client Error for http://docker:2375/version: Bad Request ("Client sent an HTTP request to an HTTPS server.")
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 275, in _raise_for_status
     response.raise_for_status()
   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1026, in raise_for_status
     raise HTTPError(http_error_msg, response=self)
 requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker:2375/version
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 223, in _retrieve_server_version
     return self.version(api_version=False)["ApiVersion"]
   File "/usr/local/lib/python3.9/site-packages/docker/api/daemon.py", line 181, in version
     return self._result(self._get(url), json=True)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 281, in _result
     self._raise_for_status(response)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 277, in _raise_for_status
     raise create_api_error_from_http_exception(e) from e
   File "/usr/local/lib/python3.9/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
     raise cls(e, response=response, explanation=explanation) from e
 docker.errors.APIError: 400 Client Error for http://docker:2375/version: Bad Request ("Client sent an HTTP request to an HTTPS server.")
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/app/app.py", line 8, in <module>
     client = docker.DockerClient(base_url='tcp://docker:2375')
   File "/usr/local/lib/python3.9/site-packages/docker/client.py", line 45, in __init__
     self.api = APIClient(*args, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 207, in __init__
     self._version = self._retrieve_server_version()
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 230, in _retrieve_server_version
     raise DockerException(
 docker.errors.DockerException: Error while fetching server API version: 400 Client Error for http://docker:2375/version: Bad Request ("Client sent an HTTP request to an HTTPS server.")
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 275, in _raise_for_status
     response.raise_for_status()
   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1026, in raise_for_status
     raise HTTPError(http_error_msg, response=self)
 requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker:2375/version
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 223, in _retrieve_server_version
     return self.version(api_version=False)["ApiVersion"]
   File "/usr/local/lib/python3.9/site-packages/docker/api/daemon.py", line 181, in version
     return self._result(self._get(url), json=True)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 281, in _result
     self._raise_for_status(response)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 277, in _raise_for_status
     raise create_api_error_from_http_exception(e) from e
   File "/usr/local/lib/python3.9/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
     raise cls(e, response=response, explanation=explanation) from e
 docker.errors.APIError: 400 Client Error for http://docker:2375/version: Bad Request ("Client sent an HTTP request to an HTTPS server.")
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/app/app.py", line 8, in <module>
     client = docker.DockerClient(base_url='tcp://docker:2375')
   File "/usr/local/lib/python3.9/site-packages/docker/client.py", line 45, in __init__
     self.api = APIClient(*args, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 207, in __init__
     self._version = self._retrieve_server_version()
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 230, in _retrieve_server_version
     raise DockerException(
 docker.errors.DockerException: Error while fetching server API version: 400 Client Error for http://docker:2375/version: Bad Request ("Client sent an HTTP request to an HTTPS server.")
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 275, in _raise_for_status
     response.raise_for_status()
   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1026, in raise_for_status
     raise HTTPError(http_error_msg, response=self)
 requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker:2375/version
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 223, in _retrieve_server_version
     return self.version(api_version=False)["ApiVersion"]
   File "/usr/local/lib/python3.9/site-packages/docker/api/daemon.py", line 181, in version
     return self._result(self._get(url), json=True)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 281, in _result
     self._raise_for_status(response)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 277, in _raise_for_status
     raise create_api_error_from_http_exception(e) from e
   File "/usr/local/lib/python3.9/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
     raise cls(e, response=response, explanation=explanation) from e
 docker.errors.APIError: 400 Client Error for http://docker:2375/version: Bad Request ("Client sent an HTTP request to an HTTPS server.")
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/app/app.py", line 8, in <module>
     client = docker.DockerClient(base_url='tcp://docker:2375')
   File "/usr/local/lib/python3.9/site-packages/docker/client.py", line 45, in __init__
     self.api = APIClient(*args, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 207, in __init__
     self._version = self._retrieve_server_version()
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 230, in _retrieve_server_version
     raise DockerException(
 docker.errors.DockerException: Error while fetching server API version: 400 Client Error for http://docker:2375/version: Bad Request ("Client sent an HTTP request to an HTTPS server.")




sudo docker inspect b47989baa34548b05da569edb5b11a149c80bff537fc3250b229a9e5a615a12f[
    {
        "Id": "b47989baa34548b05da569edb5b11a149c80bff537fc3250b229a9e5a615a12f",
        "Created": "2025-11-01T16:11:37.49705404Z",
        "Path": "python",
        "Args": [
            "app.py"
        ],
        "State": {
            "Status": "restarting",
            "Running": true,
            "Paused": false,
            "Restarting": true,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2025-11-01T16:12:08.260237644Z",
            "FinishedAt": "2025-11-01T16:12:08.970311728Z"
        },
        "Image": "sha256:a39ca6f4f2944e99379f99f2fac00c78d6ec10390715ccb59250865b6ae656ca",
        "ResolvConfPath": "/var/lib/docker/containers/b47989baa34548b05da569edb5b11a149c80bff537fc3250b229a9e5a615a12f/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/b47989baa34548b05da569edb5b11a149c80bff537fc3250b229a9e5a615a12f/hostname",
        "HostsPath": "/var/lib/docker/containers/b47989baa34548b05da569edb5b11a149c80bff537fc3250b229a9e5a615a12f/hosts",
        "LogPath": "/var/lib/docker/containers/b47989baa34548b05da569edb5b11a149c80bff537fc3250b229a9e5a615a12f/b47989baa34548b05da569edb5b11a149c80bff537fc3250b229a9e5a615a12f-json.log",
        "Name": "/vulnerable_app",
        "RestartCount": 9,
        "Driver": "overlayfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "custom_no_tool_default",
            "PortBindings": {
                "5000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5000"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "label=disable"
            ],
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": null,
            "Name": "overlayfs"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "b47989baa345",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "5000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "DOCKER_HOST=tcp://docker:2375",
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568",
                "PYTHON_VERSION=3.9.25",
                "PYTHON_SHA256=00e07d7c0f2f0cc002432d1ee84d2a40dae404a99303e3f97701c10966c91834"
            ],
            "Cmd": [
                "python",
                "app.py"
            ],
            "Image": "vulnerable_app:latest",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "721b2bf44ba2df37e343c2b96022f03d1f6136c91cb57f1bfd971029d7c63566",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "docker:service_started:false",
                "com.docker.compose.image": "sha256:a39ca6f4f2944e99379f99f2fac00c78d6ec10390715ccb59250865b6ae656ca",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "custom_no_tool",
                "com.docker.compose.project.config_files": "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2021-26120/custom_no_tool/docker-compose.yml",
                "com.docker.compose.project.working_dir": "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2021-26120/custom_no_tool",
                "com.docker.compose.service": "vulnerable_app",
                "com.docker.compose.version": "2.40.2",
                "desktop.docker.io/wsl-distro": "Ubuntu"
            },
            "StopTimeout": 1
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "SandboxKey": "",
            "Ports": {},
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "custom_no_tool_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "vulnerable_app",
                        "vulnerable_app"
                    ],
                    "MacAddress": "",
                    "DriverOpts": null,
                    "GwPriority": 0,
                    "NetworkID": "e3fa0664563b7de23b0bd6de4ceae5b85ff8a24ae5b8ffe536f4db8abe63cf7f",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DNSNames": [
                        "vulnerable_app",
                        "b47989baa345"
                    ]
                }
            }
        },
        "ImageManifestDescriptor": {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:5c606cc592eda864e6b954c004ed4a8ec4d0d263d5c857ea8c95b308a9ea6dc0",
            "size": 1622,
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        }
    }
]