time="2025-10-29T20:00:19+01:00" level=warning msg="/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2019-14234/custom_no_tool/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
#1 [internal] load local bake definitions
#1 reading from stdin 775B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile:
#2 transferring dockerfile: 152B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/python:3.9-slim
#3 DONE 0.5s

#4 [internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [1/4] FROM docker.io/library/python:3.9-slim@sha256:545badebace9a958b98d3e272f0f0d46c0a1a389ac77e24c33f2e7b548ce1b6b
#5 resolve docker.io/library/python:3.9-slim@sha256:545badebace9a958b98d3e272f0f0d46c0a1a389ac77e24c33f2e7b548ce1b6b 0.0s done
#5 DONE 0.0s

#6 [internal] load build context
#6 transferring context: 695B done
#6 DONE 0.0s

#7 [2/4] WORKDIR /app
#7 CACHED

#8 [3/4] COPY exploit.py .
#8 CACHED

#9 [4/4] RUN pip install docker==4.4.4
#9 CACHED

#10 exporting to image
#10 exporting layers done
#10 exporting manifest sha256:8d05c110a3c5f7f8276736dc97cc306a10df981fcba6d42b9569cddc454f5dd7 0.0s done
#10 exporting config sha256:14ffee6174b87b0e8bbd77507ef8751accddf9871b550eacc9ee2843e491646f 0.0s done
#10 exporting attestation manifest sha256:fd0853fd2a0190a71d422d17fc06b110d1c5f424484ce971ebe3ee67e0420a6d 0.0s done
#10 exporting manifest list sha256:5acd7b31d9fdf410f6391b7ced282a81a2ac1f05926f3d68679598780f245a35
#10 exporting manifest list sha256:5acd7b31d9fdf410f6391b7ced282a81a2ac1f05926f3d68679598780f245a35 0.0s done
#10 naming to docker.io/library/custom_no_tool-attacker_client:latest done
#10 unpacking to docker.io/library/custom_no_tool-attacker_client:latest
#10 unpacking to docker.io/library/custom_no_tool-attacker_client:latest 0.3s done
#10 DONE 0.4s

#11 resolving provenance for metadata file
#11 DONE 0.0s
 custom_no_tool-attacker_client  Built
 Network custom_no_tool_default  Creating
 Network custom_no_tool_default  Created
 Volume custom_no_tool_docker_data  Creating
 Volume custom_no_tool_docker_data  Created
 Container custom_no_tool-vulnerable_docker-1  Creating
 Container custom_no_tool-vulnerable_docker-1  Created
 Container custom_no_tool-attacker_client-1  Creating
 Container custom_no_tool-attacker_client-1  Created
 Container custom_no_tool-vulnerable_docker-1  Starting
 Container custom_no_tool-vulnerable_docker-1  Started
 Container custom_no_tool-attacker_client-1  Starting
 Container custom_no_tool-attacker_client-1  Started


sudo docker logs 87f285340d98694d0693d15282914773422d7d2633a4cff7400f64c050b9b3f2 --details
STDOUT: 
STDERR:  Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 610, in send
     conn = self.get_connection_with_tls_context(
   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 466, in get_connection_with_tls_context
     conn = self.poolmanager.connection_from_host(
   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 319, in connection_from_host
     return self.connection_from_context(request_context)
   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 341, in connection_from_context
     raise URLSchemeUnknown(scheme)
 urllib3.exceptions.URLSchemeUnknown: Not supported URL scheme http+docker
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
     return self.version(api_version=False)["ApiVersion"]
   File "/usr/local/lib/python3.9/site-packages/docker/api/daemon.py", line 181, in version
     return self._result(self._get(url), json=True)
   File "/usr/local/lib/python3.9/site-packages/docker/utils/decorators.py", line 46, in inner
     return f(self, *args, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 237, in _get
     return self.get(url, **self._set_request_timeout(kwargs))
   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
     return self.request("GET", url, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
     resp = self.send(prep, **send_kwargs)
   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
     r = adapter.send(request, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 614, in send
     raise InvalidURL(e, request=request)
 requests.exceptions.InvalidURL: Not supported URL scheme http+docker
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/app/exploit.py", line 5, in <module>
     client = docker.from_env()
   File "/usr/local/lib/python3.9/site-packages/docker/client.py", line 96, in from_env
     return cls(
   File "/usr/local/lib/python3.9/site-packages/docker/client.py", line 45, in __init__
     self.api = APIClient(*args, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 197, in __init__
     self._version = self._retrieve_server_version()
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
     raise DockerException(
 docker.errors.DockerException: Error while fetching server API version: Not supported URL scheme http+docker




sudo docker inspect 87f285340d98694d0693d15282914773422d7d2633a4cff7400f64c050b9b3f2[
    {
        "Id": "87f285340d98694d0693d15282914773422d7d2633a4cff7400f64c050b9b3f2",
        "Created": "2025-10-29T19:00:20.892493352Z",
        "Path": "python",
        "Args": [
            "/app/exploit.py"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2025-10-29T19:00:21.2409505Z",
            "FinishedAt": "2025-10-29T19:00:22.626916117Z"
        },
        "Image": "sha256:5acd7b31d9fdf410f6391b7ced282a81a2ac1f05926f3d68679598780f245a35",
        "ResolvConfPath": "/var/lib/docker/containers/87f285340d98694d0693d15282914773422d7d2633a4cff7400f64c050b9b3f2/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/87f285340d98694d0693d15282914773422d7d2633a4cff7400f64c050b9b3f2/hostname",
        "HostsPath": "/var/lib/docker/containers/87f285340d98694d0693d15282914773422d7d2633a4cff7400f64c050b9b3f2/hosts",
        "LogPath": "/var/lib/docker/containers/87f285340d98694d0693d15282914773422d7d2633a4cff7400f64c050b9b3f2/87f285340d98694d0693d15282914773422d7d2633a4cff7400f64c050b9b3f2-json.log",
        "Name": "/custom_no_tool-attacker_client-1",
        "RestartCount": 0,
        "Driver": "overlayfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/var/run/docker.sock:/var/run/docker.sock:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "custom_no_tool_default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "label=disable"
            ],
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": null,
            "Name": "overlayfs"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "87f285340d98",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "DOCKER_HOST=unix:///var/run/docker.sock",
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568",
                "PYTHON_VERSION=3.9.24",
                "PYTHON_SHA256=668391afabd5083faafa4543753d190f82f33ce6ba22d6e9ac728b43644b278a"
            ],
            "Cmd": [
                "python",
                "/app/exploit.py"
            ],
            "Image": "custom_no_tool-attacker_client",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "b78a529ffc2d22918e348820ce1c17664d17da6789ca41f9933d1c2b09317ab9",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "vulnerable_docker:service_started:false",
                "com.docker.compose.image": "sha256:5acd7b31d9fdf410f6391b7ced282a81a2ac1f05926f3d68679598780f245a35",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "custom_no_tool",
                "com.docker.compose.project.config_files": "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2019-14234/custom_no_tool/docker-compose.yml",
                "com.docker.compose.project.working_dir": "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2019-14234/custom_no_tool",
                "com.docker.compose.service": "attacker_client",
                "com.docker.compose.version": "2.40.2",
                "desktop.docker.io/wsl-distro": "Ubuntu"
            },
            "StopTimeout": 1
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "SandboxKey": "",
            "Ports": {},
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "custom_no_tool_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "custom_no_tool-attacker_client-1",
                        "attacker_client"
                    ],
                    "MacAddress": "",
                    "DriverOpts": null,
                    "GwPriority": 0,
                    "NetworkID": "3fd6b5a8c3f46c6dcb8825c64012a12e43c71fe935c5b018c47a83bb522ae998",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DNSNames": [
                        "custom_no_tool-attacker_client-1",
                        "attacker_client",
                        "87f285340d98"
                    ]
                }
            }
        },
        "ImageManifestDescriptor": {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:8d05c110a3c5f7f8276736dc97cc306a10df981fcba6d42b9569cddc454f5dd7",
            "size": 1622,
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        }
    }
]